services:
  backend:
    build: ./backend
    container_name: ats_backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    command: ["node", "server.js"]

  frontend:
    build: ./frontend
    container_name: ats_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    command: ["npm", "run", "dev", "--", "--host"]
    volumes:
    - ./frontend:/app:cached
    - /app/node_modules
